---
- name: Install Django app
  hosts: troyka
  gather_facts: true
  become: true

  vars:
    app_user_name: "troyka"
    app_user_pass: "!vault |
          $ANSIBLE_VAULT;1.1;AES256
          36666138646233303063663365356536343064366632633435653161643264306166393262376637
          6133303162383135306239353064633030636338373030360a333332643361366165643434643035
          38373030633037303938383239393135653934633334663637373162336439626136386164646235
          3235653030616665390a316462613331666664343663666633333962643963633264653534616235
          3363"
    key: "https://github.com/jtprog.keys"
    group: "admins"
    bash_profile_content: |
      export HISTTIMEFORMAT="%d/%m/%y %T "
      source ~/.bashrc

    myvimrc: |
      syntax on
      colorscheme industry
      set number
      set expandtab
      set tabstop=4
      set enc=utf-8
      set guicursor=n-v-c:block-Cursor
      set hlsearch
      set incsearch
    src_repo_url: "https://github.com/Linkor-35/django-photo.git"
    repository_branche_name: "master"
    src_repo_dest: "/home/{{app_user_name}}/app"


  tasks:

    - name: "скачиваем свежую версию из git."
      git:
        repo: "{{ src_repo_url }}"
        accept_hostkey: true
        dest: "{{ src_repo_dest }}"
        version: "{{ repository_branche_name }}"
        update: true
        force: true
      register: repo_clone
      become: true
      become_user: "{{ app_user_name }}"

    - name: "создаем для начала группу для пользователя"
      group:
        name: "{{ sysops_employer.group }}"
        state: present

    - name: "создаем учетную запись пользователя под которым будем ходить на сервер"
      user:
        name: "{{ sysops_employer.name }}"
        shell: /bin/bash
        groups: "{{ sysops_employer.group }}"
        password: "{{ sysops_employer.pass | password_hash('sha512') }}"
        update_password: on_create

    - name: "правим файл sudoers и проверяем его перед сохранением"
      lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^%{{ sysops_employer.group }} ALL='
        line: '%{{ sysops_employer.group }} ALL=(ALL) NOPASSWD: ALL'
        validate: /usr/sbin/visudo -cf %s

    - name: "добавляем созданному пользователю свой ключ"
      authorized_key:
        user: "{{ sysops_employer.name }}"
        key: "{{ sysops_employer.key }}"

    - name: "Create .bash_profile"
      copy:
        dest: "/home/{{ sysops_employer.name }}/.bash_profile"
        content: "{{ bash_profile_content }}"

    - name: "Add bashrc to bash_profile."
      lineinfile:
        path: "/home/{{ sysops_employer.name }}/.bash_profile"
        line: 'source ~/.bashrc'
        state: present

    - name: "Fix fuckup from AWX."
      lineinfile:
        path: "/home/{{ sysops_employer.name }}/.bash_profile"
        regexp: '^ssh-rsa*'
        state: absent

    - name: "Install VIM."
      package:
        name: vim
        state: latest

    - name: "Create .vimrc."
      copy:
        dest: "{{ item }}"
        content: "{{ myvimrc }}"
      with_items:
        - "/home/{{ sysops_employer.name }}/.vimrc"
