---
- name: Install Django app
  hosts: troyka
  gather_facts: true
  become: true
  become_user: root

  vars:
    app_user_name: "troyka"
    app_user_pass: "!vault |
          $ANSIBLE_VAULT;1.1;AES256
          36666138646233303063663365356536343064366632633435653161643264306166393262376637
          6133303162383135306239353064633030636338373030360a333332643361366165643434643035
          38373030633037303938383239393135653934633334663637373162336439626136386164646235
          3235653030616665390a316462613331666664343663666633333962643963633264653534616235
          3363"
    app_user_keys:
      - "https://github.com/jtprog.keys"
      - "https://github.com/Linkor-35.keys"

    app_user_group: "admins"
    app_user_bash_profile_content: "bash_profile"
    app_user_vimrc: "vimrc"

    deploy_src_repo_url: "https://github.com/Linkor-35/django-photo.git"
    deploy_src_repo_dest: "/home/{{ app_user_name }}/app"
    deploy_src_work_dir: "{{ deploy_src_repo_dest }}/src"
    deploy_repository_branche_name: "cicd"

    run_site_domain: "troyka-foto.ru"
    run_site_host: "127.0.0.1"
    run_site_port: 8000
    run_site_gunicorn_dest: "{{ deploy_src_work_dir }}/gunicorn.py"
    run_site_pid: /var/tmp/troyka.pid
    run_site_nginx_default: "/etc/nginx/conf.d/default.conf"
    run_site_systemd_unit: "/etc/systemd/system/{{ run_site_domain }}.service"
    run_site_secret_key: "$up3RseCR37"
    run_site_allowed_hosts:
      - "127.0.0.1"
      - "{{ run_site_host }}:{{ run_site_port }}"
      - "{{ run_site_domain }}"


  tasks:
    - name: NGINX
      include_tasks: ./tasks/install-nginx.yml

    - name: Prepare
      include_tasks: ./tasks/prepare.yml

    - name: Clone
      include_tasks: ./tasks/clone.yml

    - name: RUN
      include_tasks: ./tasks/run.yml
