---
- name: "RUN | install requirements in virtual environment"
  pip:
     requirements: "{{ deploy_src_repo_dest }}/requirements.txt"
     virtualenv: "{{ deploy_src_repo_dest }}/venv"
     virtualenv_command: "{{ ansible_python_interpreter }} -m venv"
