# Generated by Django 3.1.4 on 2021-01-03 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_uidd', models.CharField(max_length=36, verbose_name='ID заказа')),
                ('photo_size', models.CharField(max_length=10, verbose_name='Размер фото')),
                ('photo_type', models.BooleanField()),
                ('img', models.ImageField(upload_to='photos/', verbose_name='Загрузка фото')),
            ],
        ),
    ]
