# Generated by Django 3.1.4 on 2021-01-03 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказы', 'verbose_name_plural': 'Заказ'},
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default='', max_length=12, verbose_name='Телефон для связи'),
        ),
        migrations.AlterField(
            model_name='order',
            name='photo_type',
            field=models.BooleanField(verbose_name='Матовая?'),
        ),
    ]
