# Generated by Django 3.1.4 on 2021-01-03 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210103_2237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_uidd',
        ),
    ]
