# Generated by Django 3.1.4 on 2021-01-04 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_order_order_uidd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='img',
        ),
        migrations.RemoveField(
            model_name='order',
            name='photo_size',
        ),
        migrations.RemoveField(
            model_name='order',
            name='photo_type',
        ),
        migrations.AddField(
            model_name='order',
            name='is_done',
            field=models.BooleanField(default=False, verbose_name='Выполнен?'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_uidd',
            field=models.CharField(default='4017923177', max_length=9, verbose_name='Идентификатор'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Телефон для связи'),
        ),
    ]
