# Generated by Django 3.1.4 on 2021-01-06 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210106_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_uidd',
            field=models.CharField(default='29909', max_length=5, verbose_name='Идентификатор заказа'),
        ),
    ]
