# Generated by Django 3.1.4 on 2021-01-04 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210104_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_uidd',
            field=models.CharField(default='145603106', max_length=10, verbose_name='Идентификатор'),
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_size', models.CharField(choices=[('10x15', '10x15'), ('15x21', '15x21'), ('21x30', '21x30'), ('30x40', '30x40'), ('30x45', '30x45')], default=('10x15', '10x15'), max_length=10, verbose_name='Размер фото')),
                ('photo_type', models.BooleanField(verbose_name='Матовая?')),
                ('img', models.ImageField(upload_to='photos/', verbose_name='Загрузка фото')),
                ('phone', models.CharField(default='', max_length=12, verbose_name='Телефон для связи')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.order')),
            ],
            options={
                'verbose_name': 'Заказы',
                'verbose_name_plural': 'Заказ',
            },
        ),
    ]
