# Generated by Django 3.1.4 on 2021-01-04 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210104_1427'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'verbose_name': 'Фотографии', 'verbose_name_plural': 'Фотография'},
        ),
        migrations.RemoveField(
            model_name='photo',
            name='img',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='phone',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_uidd',
            field=models.CharField(default='1003114678', max_length=10, verbose_name='Идентификатор'),
        ),
    ]
