# Generated by Django 3.1.4 on 2021-01-04 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210104_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='img',
            field=models.ImageField(default=111, upload_to='photos/', verbose_name='Загрузка фото'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='order_uidd',
            field=models.CharField(default='4142344505', max_length=10, verbose_name='Идентификатор'),
        ),
    ]
