# Generated by Django 3.1.4 on 2021-01-04 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210104_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='count',
            field=models.IntegerField(default=1, verbose_name='Кол-во'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_uidd',
            field=models.CharField(default='186330626', max_length=10, verbose_name='Идентификатор'),
        ),
    ]
