# Generated by Django 3.1.4 on 2021-01-04 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210104_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='photo_uuid',
            field=models.CharField(default='2213892162', max_length=10, verbose_name='Идентификатор'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_uidd',
            field=models.CharField(default='3308101030', max_length=10, verbose_name='Идентификатор'),
        ),
    ]
