# Generated by Django 3.1.4 on 2021-01-06 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210106_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_uidd',
        ),
    ]
