name: Release

'on':
  push:
    tags:
      - '*'


jobs:
  release:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.x]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        pip install --upgrade pip setuptools wheel
        pip install -r requirements.txt

    - name: Run Tests
      run: |
        cd src/
        python manage.py test

    - name: Install ansible
      run: |
        pip install ansible
        ansible --version

    - name: Get vault password
      run: |
        echo ${{ secrets.ANSIBLE_VAULT_PASS }} > .cicd/.vault_pass

    - name: Run deploy
      uses: dawidd6/action-ansible-playbook@v2
      with:
        playbook: site.yml
        directory: .cicd/
        key: ${{ secrets.ANSIBLE_SSH_PK }}
        # inventory: |
        #   [all]
        #   example.com
        #
        #   [group1]
        #   example.com
        vault_password: ${{ secrets.ANSIBLE_VAULT_PASS }}
        options: |
          --verbose
          -vault-password-file=./.vault_pass

    # - name: Run deploy
    #   run: |
    #     echo ${{ secrets.ANSIBLE_VAULT_PASS }} > .cicd/.vault_pass
    #     echo ${{ secrets.ANSIBLE_SSH_PK }} > ~/.ssh/id_rsa
    #     cd .cicd/
    #     ansible-playbook site.yml --vault-password-file=./.vault_pass
    #
    #   env:
    #     PY_COLORS: '1'
